pipeline {
    agent any

    tools {
        jdk 'jdk17'
        maven 'M3'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Baixando código-fonte...'
                git branch: 'main', url: 'https://github.com/rafael-blomer/EstoqueALIS.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Compilando o projeto...'
                dir('EstoqueALIS') {
                    bat 'mvn -B clean package -DskipTests'
                }
            }
        }

        stage('Testes') {
            steps {
                echo 'Executando testes...'
                dir('EstoqueALIS') {
                    bat 'mvn test'
                }
            }
        }

        stage('Arquivar artefato') {
            steps {
                echo 'Arquivando artefatos gerados...'
                dir('EstoqueALIS') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo '✅ Build concluído com sucesso!'
        }
        failure {
            echo '❌ Falha no build!'
        }
    }
}
